### ISSUE TITLE
Do not work with Django 2.1.2

### ISSUE THREAD

**Issue by Phill93** [jazzband/django-simple-menu#55]
This Module do not work with Django Version 2.1.2 and Python 3.7.

```Traceback (most recent call last):
  File "/Users/User/projects/product/venv/lib/python3.7/site-packages/django/template/base.py", line 850, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [blubb] in {}
Exception while resolving variable 'main' in template 'index.html'.
Traceback (most recent call last):
  File "/Users/rt1330/projects/iaiHub/venv/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
KeyError: 'main'
```

**Comment by Phill93** [comment]
Sorry forget this i had an error else where
